"$schema" = "./node_modules/wrangler/config-schema.json"
name = "oauth-proxy"
main = "src/index.ts"
compatibility_date = "2026-05-06"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
send_metrics = false

[observability]
enabled = true
head_sampling_rate = 1

[[ratelimits]]
name = "RATE_LIMIT"
namespace_id = "983240"
# Not sure if this is too strict or too lax; observations needed.
simple = { limit = 30, period = 60 }
